server:
  port: 8003
  servlet:
    context-path: /buos-task
spring:
  main:
     allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    showsql: true
    hibernate: 
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 2
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:mysql://dev01.drplt.com:3306/dp_baseinfo2?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: dp_baseinfo_t_u
    password: dp_baseinfo_t_p
    driverClassName: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    maxWaitMillis: 3330000      
    minIdle: 3
    maxIdle: 10
    maxTotal: 20
    initialSize: 5
    validationQuery: SELECT 1    
    initialization-mode: always